# ==========================================================
# Neura-X: Intelligence Without Limits.
# Copyright (c) 2026 Edusei Mikel Lisamba. All Rights Reserved.
# ==========================================================

github: [mikeledusei]
custom:
  - "https://neura-x.dev/support"
